sudo: required
dist: bionic
jdk: openjdk11
services: docker
matrix:
  fast_finish: true

addons:
  apt:
    packages:
      - graphviz
      
install:
  - curl -s https://get.nextflow.io | bash

env:
  - NXF_VER='19.10.0' # Minimum NF version
  #- NXF_VER='' # Latest NF version 

before_script:
  - wget https://github.com/plantinformatics/pretzel-input-generator/releases/download/testdata/test-data.tar.gz
  - tar xzvf test-data.tar.gz 

script:
  - ./nextflow run main.nf -profile test,docker --max_cpus 2 --max_memory 4.GB -ansi-log false