name: CI

on: [push]

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Install GraphViz
        run: |
          sudo apt-get update && sudo apt-get install -y graphviz
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Check out code
        uses: actions/checkout@v1
      - name: Test workflow (docker)
        run: |
          NXF_VER=19.10.0 nextflow run ${GITHUB_WORKSPACE} -profile CI,docker --max_cpus 2 --max_memory 4.GB -ansi-log false

  singularity:
    runs-on: ubuntu-18.04
    # runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup SIngularity
        uses: eWaterCycle/setup-singularity@v5
        with:
          singularity-version: 3.6.4
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Pull containers
        run: |
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          nextflow run ${GITHUB_WORKSPACE}/pull_containers.nf -ansi-log false -profile singularity
      - name: Test workflow  (singularity)
        run: |
          NXF_VER=19.10.0 nextflow run ${GITHUB_WORKSPACE} -profile CI,singularity --max_cpus 2 --max_memory 4.GB -ansi-log false