name: CI

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1    
      - name: Install GraphViz
        run: |
          sudo apt-get update && sudo apt-get install -y \          
            graphviz
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Test Nextflow
        run: |          
          NXF_VER=19.10.0 nextflow -version
      - name: Get test data 
        run: |
          wget https://github.com/plantinformatics/pretzel-input-generator/releases/download/testdata/test-data.tar.gz
          tar xzvf test-data.tar.gz 
      - name: Test workflow (docker) 
        run: |
          NXF_VER=19.10.0 nextflow run ${GITHUB_WORKSPACE} -profile test,docker --max_cpus 2 --max_memory 4.GB -ansi-log false

  singularity:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1        
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Install Dependencies for Singularity (and GraphViz)
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            pkg-config \
            graphviz
      - name: Install Singularity
        env:
          SINGULARITY_VERSION: 3.5.2
        run: |
          export GOPATH=/tmp/go
          mkdir -p $GOPATH
          sudo mkdir -p /usr/local/var/singularity/mnt && \
          mkdir -p $GOPATH/src/github.com/sylabs && \
          cd $GOPATH/src/github.com/sylabs && \
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz | \
          tar xzv && \
          cd singularity && \
          ./mconfig -p /usr/local && \
          make -C builddir && \
          sudo make -C builddir install
      - name: Test Singularity pull from Docker 
        run: |
          singularity pull --name hello.img docker://hello-world > /dev/null
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Test Nextflow
        run: |          
          NXF_VER=19.10.0 nextflow -version
      # - name: Get test data 
      #   run: |
      #     wget https://github.com/plantinformatics/pretzel-input-generator/releases/download/testdata/test-data.tar.gz
      #     tar xzvf test-data.tar.gz 
      - name: Pull containers 
        run: |
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          nextflow run ${GITHUB_WORKSPACE}/pull_containers.nf -ansi-log false -profile singularity
      - name: Test workflow  (singularity)
        run: |
          NXF_VER=19.10.0 nextflow run ${GITHUB_WORKSPACE} -profile MICROSPORIDIA,singularity --max_cpus 2 --max_memory 4.GB -ansi-log false
      # - name: Test workflow (docker) 
      #   run: |
      #     NXF_VER=19.10.0 nextflow run ${GITHUB_WORKSPACE} -profile test,docker --max_cpus 2 --max_memory 4.GB -ansi-log false       
